//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbLibraryEntities : DbContext
    {
        public dbLibraryEntities()
            : base("name=dbLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBook> tblBooks { get; set; }
        public virtual DbSet<tblBorrowed> tblBorroweds { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<viewUpgradedBook> viewUpgradedBooks { get; set; }
        public virtual DbSet<viewUpgradedUser> viewUpgradedUsers { get; set; }
        public virtual DbSet<viewUpgradedBorrowed> viewUpgradedBorroweds { get; set; }
    
        public virtual int giveBackBook(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("giveBackBook", pidParameter);
        }
    }
}
