//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblBorroweds = new HashSet<tblBorrowed>();
        }
    
        public int usrID { get; set; }
        public string usrName { get; set; }
        public string usrSurname { get; set; }
        public string usrSchoolNumber { get; set; }
        public string usrMail { get; set; }
        public string usrPassword { get; set; }
        public string usrAuthorityLevel { get; set; }
        public bool usrAccountActivation { get; set; }
        public Nullable<bool> usrLecturerActivation { get; set; }
        public byte usrAmontBooks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBorrowed> tblBorroweds { get; set; }
    }
}
