//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewUpgradedBook
    {
        public int bkID { get; set; }
        public string bkName { get; set; }
        public string bkAuthor { get; set; }
        public int bkPages { get; set; }
        public System.DateTime bkPublishedDate { get; set; }
        public string ctgName { get; set; }
        public string bkSummary { get; set; }
        public byte bkAmount { get; set; }
    }
}
